# Generated by Django 4.2.1 on 2023-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_alumno_profesor_infoalumno_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='autor',
        ),
        migrations.AddField(
            model_name='clase',
            name='contenido',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='imagen',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=60, null=True, verbose_name='nombre'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
