# Generated by Django 4.2.1 on 2023-06-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_remove_entrada_autor_remove_tecnologia_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='contenido',
            field=models.TextField(default=2, max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='exit', max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripccion', models.CharField(max_length=500)),
                ('fecha_de_entrega', models.TextField(max_length=600)),
                ('nombre_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articulos.clase')),
            ],
        ),
    ]
