# Generated by Django 4.2.1 on 2023-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='mail',
            field=models.EmailField(max_length=90, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=500, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=90, verbose_name='Nombre'),
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='mensaje',
        ),
    ]
