# Generated by Django 4.2.1 on 2023-05-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0005_comentario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollador', models.CharField(max_length=100, verbose_name='Desarrollador')),
            ],
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='id',
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Articulos.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cometo', models.BooleanField(verbose_name='Ha comentado')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articulos.comentario')),
            ],
        ),
        migrations.AlterField(
            model_name='entrada',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Articulos.autor'),
        ),
    ]
