# Generated by Django 4.1.4 on 2022-12-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_rename_imgenes_entrada_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('comentario', models.TextField(max_length=500)),
            ],
        ),
    ]
